# <!-- Powered by BMAD™ Core -->
name: bmad-ai-agent-dev
version: 1.0.0
short-title: AI Agent Development Studio
description: >-
  Comprehensive AI agent development framework based on MongoDB's CANVAS
  methodology. Guides teams through systematic agent planning, validation,
  and production deployment using Product → Agent → Data → Model flow.
  Includes 10 specialized agents (planning, implementation, and governance),
  POC and Production canvas templates, validation checklists, and complete
  workflows from ideation to enterprise deployment. Prevents the 6 critical
  failure patterns killing 95% of AI agent projects.
author: BMAD Method Community
slashPrefix: bmad-agent
